<div class="bootstrap rublon-allow-tracking-header">
	<img id="rublon-allow-tracking-logo-img" alt=""
		src="<?php echo $logo_url; ?>">
	<h3><?php echo $path; ?></h3>
</div>

<div class="rublon-container">

<div id="rublon-api-reg-container">
					
		<div class="rublon-apireg-half-column rublon-apireg-description">
            <p>
                <h3>Please wait, Rublon is configuring API credentials...</h3>
            </p>			
		</div>	
	<div class="rublon-apireg-half-column rublon-apireg-image">
		<img src="<?php echo $rublon_visual_url; ?>"
			class="rublon-apireg-visual rublon-image">

	</div>
</div>

</div>

<?php echo $registration_form_hidden; ?>